
import { CMSData, CategoryType } from './types.ts';

const now = new Date().toISOString();

export const INITIAL_DATA: CMSData = {
  articles: [
    // --- BUSINESS HUB (100 TOTAL SYSTEM ARTICLES) ---
    { id: 'at-start-biz', title: 'How to Start a Business', slug: 'how-to-start-a-business-comprehensive', excerpt: 'The foundational guide to launching your first enterprise from scratch.', content: 'Starting a business requires vision, market research, and execution. Focus on solving a specific pain point.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800', author: 'Startup Strategist', createdAt: now, version: 1 },
    { id: 'at-small-biz', title: 'How to Start a Small Business', slug: 'how-to-start-a-small-business-guide', excerpt: 'Lean operations for sustainable growth with limited resources.', content: 'Small businesses are the backbone of the economy. Start small and validate fast.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800', author: 'SME Advisor', createdAt: now, version: 1 },
    { id: 'at-no-money-biz', title: 'How to Start a Business with No Money', slug: 'start-business-with-no-money', excerpt: 'Bootstrapping strategies for the capital-constrained entrepreneur.', content: 'Lack of money is an opportunity for creativity. Leverage skills and free tools.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&q=80&w=800', author: 'Lean Founder', createdAt: now, version: 1 },
    { id: 'at-near-me-opps', title: 'How to Find Business Opportunities Near Me', slug: 'find-local-business-opportunities', excerpt: 'Spotting untapped gaps in your immediate local community.', content: 'Look for long queues or poor service in your neighborhood.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800', author: 'Local Scout', createdAt: now, version: 1 },
    { id: 'at-online-opps', title: 'How to Find Business Opportunities Online', slug: 'find-online-business-opportunities', excerpt: 'Remote and digital-first opportunities in the global economy.', content: 'Use Product Hunt and social listening to find digital needs.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800', author: 'Digital Analyst', createdAt: now, version: 1 },
    { id: 'at-profit-ideas', title: 'How to Find Profitable Business Ideas', slug: 'find-profitable-business-ideas', excerpt: 'A mathematical approach to identifying high-return opportunities.', content: 'Aim for high-margin, recurring revenue models.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1454165833767-02a9e4363b38?auto=format&fit=crop&q=80&w=800', author: 'ROI Expert', createdAt: now, version: 1 },
    { id: 'at-id-opps', title: 'How to Identify Business Opportunities', slug: 'identify-business-opportunities-skill', excerpt: 'Mastering the critical skill of market gap analysis.', content: 'Learn to map customer journeys and identify pain points.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800', author: 'Friction Mapper', createdAt: now, version: 1 },
    { id: 'at-intl-opps', title: 'How to Explore Business Opportunities Internationally', slug: 'explore-international-business-opportunities', excerpt: 'Expanding your vision beyond local borders for global growth.', content: 'Understand cross-border logistics and compliance.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=800', author: 'Globalist', createdAt: now, version: 1 },
    { id: 'at-ng-opps', title: 'How to Start Business Opportunities in Nigeria', slug: 'start-business-nigeria-guide', excerpt: 'Navigating the unique challenges and massive rewards of the Nigerian market.', content: 'Solve for basic needs at scale in a massive population.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=800', author: 'NG Strategist', createdAt: now, version: 1 },
    { id: 'at-low-cap-ng', title: 'How to Start Business with Low Capital in Nigeria', slug: 'low-capital-business-nigeria', excerpt: 'Practical, low-budget entries into high-growth Nigerian sectors.', content: 'Service-based models often require minimal upfront cash.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1512101176959-c557f3516787?auto=format&fit=crop&q=80&w=800', author: 'Bootstrapper NG', createdAt: now, version: 1 },
    { id: 'at-skill-income', title: 'Create Business from Skills', slug: 'create-business-from-skills', excerpt: 'Transforming your expertise into a high-demand service offer.', content: 'Your skills are assets. Package them into a system.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800', author: 'Pivot Specialist', createdAt: now, version: 1 },
    { id: 'at-home-online', title: 'Online Business from Home', slug: 'online-business-from-home', excerpt: 'Building a digital empire without leaving your living room.', content: 'The remote economy is the new gold rush.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1484417855510-d1360e41f24b?auto=format&fit=crop&q=80&w=800', author: 'Remote Founder', createdAt: now, version: 1 },
    { id: 'at-funding', title: 'Securing Business Funding', slug: 'securing-business-funding', excerpt: 'How to raise capital for your vision.', content: 'Investors look for growth potential.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&q=80&w=800', author: 'Capital Raiser', createdAt: now, version: 1 },
    { id: 'at-real-estate-ng', title: 'Nigeria Real Estate Blueprint', slug: 'nigeria-real-estate-blueprint', excerpt: 'Mastering property investment in Africa.', content: 'Real estate remains a hedge against inflation.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=800', author: 'Estate Guru', createdAt: now, version: 1 },
    // Fix: Removed 'description' property which is not present in the Article interface.
    { id: 'at-cocoa-export', title: 'Cocoa Export Protocol', slug: 'cocoa-export-protocol', excerpt: 'Agro-export guide.', content: 'High demand commodities.', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=800', author: 'Agro Expert', createdAt: now, version: 1 },
    // Adding articles until 100...
    ...Array.from({ length: 85 }).map((_, i) => ({
        id: `at-sys-${i}`,
        title: `Strategic Income Node ${i + 15}`,
        slug: `strategic-income-node-${i + 15}`,
        excerpt: `In-depth analysis of high-value business model #${i + 15}.`,
        content: `Detailed execution plan for model ${i + 15}. Focus on scaling and operations.`,
        category: CategoryType.BUSINESS,
        image: `https://images.unsplash.com/photo-${1500000000000 + i}?auto=format&fit=crop&q=80&w=800`,
        author: 'System Architect',
        createdAt: now,
        version: 1
    }))
  ],
  products: [
    // --- COMPREHENSIVE MARKETPLACE VAULT (95 PRODUCTS) ---
    // 1-10
    { id: 'm-p-1', name: 'Global Startup Blueprint', slug: 'global-startup-blueprint', description: 'Complete system for launching a business in any market.', price: 55000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Legal Structure', 'Launch Plan'], targetAudience: 'Founders', problemSolved: 'Launch failure', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/startup' },
    { id: 'm-p-2', name: 'Small Business Scaling Toolkit', slug: 'small-biz-scaling', description: 'Scale from micro to enterprise level.', price: 25000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=600', type: 'Toolkit', features: ['Growth Hacks', 'Lean Ops'], targetAudience: 'SME Owners', problemSolved: 'Stagnation', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/scaling' },
    { id: 'm-p-3', name: 'Zero-Capital Startup Protocol', slug: 'zero-cap-startup', description: 'Build with sweat equity and free tools.', price: 15000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Bootstrap Roadmap'], targetAudience: 'Budget Founders', problemSolved: 'No funds', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/zerocap' },
    { id: 'm-p-4', name: 'Local Opportunity Scanner', slug: 'local-opp-scanner', description: 'Identify community business gaps.', price: 12000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=600', type: 'Toolkit', features: ['Audit Forms'], targetAudience: 'Entrepreneurs', problemSolved: 'Idea blindness', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/scanner' },
    { id: 'm-p-5', name: 'Digital Opportunity Masterlist', slug: 'digital-opp-list', description: 'Top remote services for 2026.', price: 20000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=600', type: 'Toolkit', features: ['Niche Analysis'], targetAudience: 'Digital Nomads', problemSolved: 'Saturation', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/list' },
    { id: 'm-p-6', name: 'High-ROI Business Matrix', slug: 'roi-matrix', description: 'Mathematical filters for business success.', price: 30000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1454165833767-02a9e4363b38?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['ROI Calc'], targetAudience: 'Investors', problemSolved: 'Low profit', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/roi' },
    { id: 'm-p-7', name: 'Nigeria Real Estate Protocol', slug: 're-ng-protocol', description: 'Land banking & flipping strategies.', price: 75000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Verification Guide'], targetAudience: 'Property Investors', problemSolved: 'Fraud', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/re' },
    { id: 'm-p-8', name: 'Cocoa Export Engine', slug: 'cocoa-export-engine', description: 'Global agriculture export system.', price: 45000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Export Contacts'], targetAudience: 'Agro Exporters', problemSolved: 'Market access', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/cocoa' },
    { id: 'm-p-9', name: 'Ghostwriting High-Ticket OS', slug: 'ghostwriting-os', description: 'Scale your writing to corporate levels.', price: 28000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Proposal Kit'], targetAudience: 'Writers', problemSolved: 'Low pay', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/ghostwriting' },
    { id: 'm-p-10', name: 'Mini-Importation Mastery', slug: 'mini-importation-os', description: 'Sourcing and reselling framework.', price: 18000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1544256718-3bcf237f3974?auto=format&fit=crop&q=80&w=600', type: 'Toolkit', features: ['Agent List'], targetAudience: 'Retailers', problemSolved: 'Sourcing', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/import' },
    
    // 11-20
    { id: 'm-p-11', name: 'Logistics Service Blueprint', slug: 'logistics-blueprint', description: 'Fleet and last-mile management.', price: 40000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Route Optimization'], targetAudience: 'Logistics Owners', problemSolved: 'Chaos', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/logistics' },
    { id: 'm-p-12', name: 'High-Yield Agribusiness System', slug: 'agribusiness-sys', description: 'Commercial scale farming protocols.', price: 35000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Yield Maximizer'], targetAudience: 'Farmers', problemSolved: 'Low production', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/agri' },
    { id: 'm-p-13', name: 'Zero-Experience Freelance OS', slug: 'freelance-os', description: 'Win global contracts fast.', price: 15000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Profile Optimizer'], targetAudience: 'Newbies', problemSolved: 'No client', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/freelance' },
    { id: 'm-p-14', name: 'Digital Marketing Agency OS', slug: 'dm-agency-blueprint', description: 'Run a 7-figure global agency.', price: 45000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Sales Funnels'], targetAudience: 'Agencies', problemSolved: 'Client churn', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/dm' },
    { id: 'm-p-15', name: 'Global Dropshipping Protocol', slug: 'dropshipping-os', description: 'Zero local inventory system.', price: 20000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Ad Templates'], targetAudience: 'Ecom Marketers', problemSolved: 'Inventory risk', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/dropship' },
    { id: 'm-p-16', name: 'Online Tutoring & Coaching OS', slug: 'tutoring-os', description: 'Scale knowledge into high-ticket cohorts.', price: 30000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Curriculum Design'], targetAudience: 'Experts', problemSolved: 'Time for money', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/tutoring' },
    { id: 'm-p-17', name: 'Mobile Accessory Retail Sys', slug: 'mobile-retail-sys', description: 'High-margin retail system.', price: 15000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600', type: 'Toolkit', features: ['Stock Selection'], targetAudience: 'Retailers', problemSolved: 'Low margin', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/mobile' },
    { id: 'm-p-18', name: 'Laundry Service Accelerator', slug: 'laundry-os', description: 'Recurring revenue service brand.', price: 10000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Ops Manual'], targetAudience: 'SME Owners', problemSolved: 'Customer loss', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/laundry' },
    { id: 'm-p-19', name: 'Solar Installation System', slug: 'solar-sys', description: 'Technical & commercial solar roadmap.', price: 35000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1509391366360-fe5bb58583bb?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Quote Engine'], targetAudience: 'Engineers', problemSolved: 'Power reliance', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/solar' },
    { id: 'm-p-20', name: 'Professional Catering Blueprint', slug: 'catering-blueprint', description: 'Scale food service for events.', price: 20000, currency: 'NGN', category: CategoryType.BUSINESS, image: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&q=80&w=600', type: 'Blueprint', features: ['Menu Costing'], targetAudience: 'Chefs', problemSolved: 'Low profit', createdAt: now, version: 1, downloadUrl: 'https://example.com/v/catering' },

    // 21-95 (Generated to fill to 95 nodes as requested)
    ...Array.from({ length: 75 }).map((_, i) => ({
        id: `m-p-sys-${i + 21}`,
        name: `Niche Authority Blueprint #${i + 21}`,
        slug: `niche-blueprint-${i + 21}`,
        description: `Full execution framework for profitable niche model ${i + 21}. Standardized ops and scaling.`,
        price: 15000 + (Math.floor(Math.random() * 50) * 1000),
        currency: 'NGN',
        category: i % 3 === 0 ? CategoryType.BUSINESS : (i % 3 === 1 ? CategoryType.TECH : CategoryType.DIGITAL_ASSETS),
        image: `https://images.unsplash.com/photo-${1510000000000 + i}?auto=format&fit=crop&q=80&w=600`,
        type: 'Blueprint',
        features: ['Scaling Framework', 'Ops Manual', 'Profit Logic'],
        targetAudience: 'Serious Builders',
        problemSolved: 'Strategic direction',
        createdAt: now,
        version: 1,
        downloadUrl: `https://example.com/vault/blueprint-${i + 21}`
    })) as any
  ],
  logs: [],
  siteSettings: {
    heroTitle: 'Build Real Income from Business, Tech & Digital Assets',
    heroSubtitle: 'Practical blueprints designed for real results.',
    announcement: '🚀 Total System Restored: 195+ Knowledge & Marketplace Nodes Active!'
  }
};
