import { CMSData, CategoryType } from './types.ts';

export const INITIAL_DATA: CMSData = {
  articles: [
    // --- TECH SECTION (7 ARTICLES) ---
    {
      id: 'a1',
      title: 'How to Make Money Online in Nigeria Without Scams (Practical Guide)',
      slug: 'make-money-online-nigeria-no-scams',
      excerpt: 'Filter the noise and focus on verified, high-yield digital skills.',
      content: 'Legitimate online income in Nigeria is built on the exchange of global value. Avoid any platform that asks for "Referral Fees" or promises returns without work. Instead, focus on freelancing, remote tech support, content creation, or digital asset trading. By using verified platforms like Upwork or Selar and focusing on earning in foreign currency, you can bypass local economic hurdles and build a sustainable, scam-free career from your laptop.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1542601906960-da0eddd7e93e?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString(),
      featured: true
    },
    {
      id: 'a3',
      title: 'How to Turn Your Skills Into a Profitable Online Business',
      slug: 'turn-skills-profitable-online-business',
      excerpt: 'Your existing knowledge is your most valuable digital currency.',
      content: 'Every professional skill—from accounting to graphic design—has an online market. The transformation starts by packaging your skill as a "Productized Service" or an "Info-Product." By creating a clear offer with a fixed price and an automated delivery system, you move from being a "Hired Hand" to a "Business Owner." This allows you to scale beyond your own hours by hiring others to execute your proven methodology.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a8',
      title: 'How to Make Money Using AI Tools Without Technical Skills',
      slug: 'make-money-ai-no-tech-skills',
      excerpt: 'Prompting is the new coding. Learn to command the machines for profit.',
      content: 'You don\'t need to know Python to profit from the AI revolution. Modern Generative AI tools allow you to fulfill complex client requests—like professional copywriting, logo design, or video editing—in a fraction of the time. The business model is simple: Sell the "Final Output" to clients who lack the time or the curiosity to learn the AI tools themselves. You act as the expert operator, delivering high-quality work at speed.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a11',
      title: 'How to Start a Digital Business With Just a Laptop and Internet',
      slug: 'digital-business-laptop-internet',
      excerpt: 'The ultimate guide to borderless entrepreneurship from anywhere.',
      content: 'A laptop-based business is the pinnacle of modern freedom. Whether it\'s managing an e-commerce store, running a SaaS platform, or building a high-traffic niche blog, the requirements are the same: a reliable connection and a high-value offer. By targeting international markets where your local cost of living is a competitive advantage, you can build a highly profitable venture that doesn\'t depend on your local economy.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a13',
      title: 'How to Start Freelancing With No Experience and Get Paid',
      slug: 'start-freelancing-no-experience',
      excerpt: 'Your first client is waiting for your potential, not your history.',
      content: 'Winning your first freelance gig without a portfolio requires the "Demonstration Strategy." Instead of a CV, send a customized sample of the work you would do for the client for free. This eliminates their risk and proves your ability. Once you have your first 3 "Yes" responses, you have a portfolio. From there, it is a matter of optimizing your profile and increasing your rates as your social proof grows.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a14',
      title: 'How to Sell Digital Products Online Step by Step',
      slug: 'sell-digital-products-step-by-step',
      excerpt: 'From creation to first sale: The definitive digital merchant roadmap.',
      content: 'The 4-step path to digital sales: 1. Identify a "Burning Problem" in a niche you understand. 2. Create a "Micro-Asset" (PDF, Template, or Audio) that solves it. 3. Set up a storefront on a platform that handles payments for you. 4. Use short-form video (TikTok/Reels) to show the transformation your product provides. Digital products have 100% margins, making them the most efficient path to wealth.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a16',
      title: 'How to Build an Online Income That Is Not Dependent on One Source',
      slug: 'independent-online-income-diversity',
      excerpt: 'Learn the "Hydra Model" of digital revenue for absolute security.',
      content: 'Relying on one platform (like YouTube or Amazon) is a business risk. To build an independent income, you must own your "Traffic and Sales" system. This means building an email list and having products on your own domain. By diversifying your traffic sources and having multiple offers at different price points, you ensure that no algorithm change or platform ban can destroy your livelihood.',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1512428559083-560dfc18b20e?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },

    // --- BUSINESS SECTION (7 ARTICLES) ---
    {
      id: 'a2',
      title: 'How to Start a Small Business With Little Capital and Grow It Fast',
      slug: 'start-small-business-little-capital',
      excerpt: 'The secret to scaling isn\'t starting big, but starting lean and moving fast.',
      content: 'Starting a business with limited capital requires a shift from asset-heavy models to service-oriented ones. By focusing on high-demand skills or low-inventory models like dropshipping or micro-retailing, you can validate your idea without financial risk. The key to fast growth is immediate reinvestment of every kobo of profit back into marketing and customer acquisition systems that work.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString(),
      featured: true
    },
    {
      id: 'a6',
      title: 'How to Find Profitable Business Ideas People Are Paying For',
      slug: 'find-profitable-business-ideas',
      excerpt: 'Stop guessing and start solving problems that already have budgets attached to them.',
      content: 'Profitable business ideas are hidden in plain sight—usually in the form of common frustrations. To identify them, look for processes that are slow, expensive, or outdated in your local market or online community. Use keyword research tools and social listening to see where people are complaining; if there is a recurring complaint, there is a profit opportunity for the person who builds a better solution.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1454165833767-027eeef1593e?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a7',
      title: 'How to Start a Side Hustle While Working a Full-Time Job',
      slug: 'start-side-hustle-full-time-job',
      excerpt: 'Balance your 9-to-5 with a 6-to-10 that eventually sets you free.',
      content: 'Managing a side hustle alongside a career is a test of discipline and automation. The strategy is to choose a business model that doesn\'t require real-time presence, such as digital products or automated service agencies. By dedicating just 2 hours every evening and 5 hours on weekends, you can build a system that generates revenue while you focus on your primary job, creating a safety net for future transition.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a9',
      title: 'How to Start a Business From Home and Earn Consistently',
      slug: 'start-business-from-home-consistently',
      excerpt: 'Your living room is the new corporate headquarters of the 21st century.',
      content: 'Consistently earning from home requires a professional routine that mimics an office environment. Focus on high-value remote services like consulting, tech support, or digital design where the overhead is zero but the billable hours are high. Use professional project management tools to stay organized and ensure you have a dedicated workspace that allows you to separate your personal life from your business growth.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a15',
      title: 'How to Start a Consulting Business Even If You’re Not an Expert',
      slug: 'start-consulting-not-expert',
      excerpt: 'You only need to be two steps ahead of your client to provide massive value.',
      content: 'Consulting is about results, not credentials. If you have solved a specific problem for yourself or a previous employer, you are already an "Expert" to someone who is still struggling with that same problem. By focusing on a specific niche—like helping small shops set up Instagram ads or teaching seniors how to use AI tools—you can provide immediate value and charge professional fees based on the time and money you save your clients.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a17',
      title: 'How to Start a Profitable Business Without Quitting Your Job',
      slug: 'profitable-business-without-quitting',
      excerpt: 'Leverage your salary to fund your dream until the dream pays more than the salary.',
      content: 'The "Safety-First" entrepreneurship model involves using your steady paycheck as your first angel investor. Instead of taking on debt, use your monthly savings to pay for software, freelancers, and small ad tests. This approach allows you to iterate and fail safely until you find a "Winning Product" that generates enough consistent cashflow to replace your salary 2x over before you even think about resigning.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a18',
      title: 'How to Turn Business Ideas Into Real Income',
      slug: 'turn-business-ideas-real-income',
      excerpt: 'Ideas are worthless without an execution framework that leads to a sale.',
      content: 'Turning an idea into income requires moving from the "Concept Phase" to the "Transaction Phase" as fast as possible. Create a Minimum Viable Product (MVP) or a simple landing page and ask people to pay for it before you spend months building. Real income starts with a single transaction; once you have one person willing to part with money for your value, you have a business—everything else is just scaling that one success.',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },

    // --- DIGITAL ASSETS SECTION (6 ARTICLES) ---
    {
      id: 'a4',
      title: 'How to Build Multiple Streams of Income as a Beginner',
      slug: 'multiple-streams-income-beginner',
      excerpt: 'Don\'t put all your financial eggs in one basket. Learn to diversify.',
      content: 'Building multiple streams is about layering different income types: Active (Service), Portfolio (Dividends), and Passive (Digital Assets). A beginner should start with one active stream to build capital, then immediately funnel that capital into assets that don\'t require time—like affiliate sites, stock market index funds, or automated digital product stores. This "Income Layering" ensures that if one source dries up, your lifestyle is protected by the others.',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString(),
      featured: true
    },
    {
      id: 'a5',
      title: 'How to Start an Online Business That Actually Works in 2026',
      slug: 'online-business-2026-strategy',
      excerpt: 'The digital landscape is changing. Here is how to stay ahead of the curve.',
      content: 'In 2026, successful online businesses are those that integrate AI agents and focus on "Deep Personalization." Generic content and basic dropshipping are dead. To win now, you must build a "Community-First" brand where you own the relationship with your audience via email or private forums. High-value digital assets and specialized SaaS tools are the highest-margin models for the next decade.',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a10',
      title: 'How to Monetize Knowledge and Experience in Simple Ways',
      slug: 'monetize-knowledge-experience',
      excerpt: 'What you know is worth more than what you do. Start selling insights.',
      content: 'Knowledge monetization is about transformation. Don\'t sell "How-To" information; sell the "Outcome." Whether it\'s a 10-page guide on how to pass a specific exam or a video course on gardening, people are paying for the shortcut. Use platforms like Selar, Gumroad, or Substack to package your unique insights into paid subscriptions or one-time downloads that provide instant value to a specific niche.',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a12',
      title: 'How to Build a Business That Generates Passive Income Over Time',
      slug: 'build-passive-income-business',
      excerpt: 'Front-load the work to enjoy back-end freedom for years to come.',
      content: 'True passive income requires a "System-First" architecture. This means building a business where the product delivery and the marketing are both automated. Content-rich websites that earn through ads or affiliate links, or software-as-a-service (SaaS) products, are the gold standard. It takes significant effort to build the machine, but once it\'s running, your primary role shifts from "Worker" to "Maintenance Engineer."',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1518433278981-11271f4a7c22?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a19',
      title: 'How to Identify Online Opportunities Before They Get Saturated',
      slug: 'identify-early-online-opportunities',
      excerpt: 'The early bird gets the Dollar. Learn to spot the next big wave.',
      content: 'Saturation is a myth for those who are early. To spot opportunities, watch the "Tech Pioneers"—look at what new APIs (like OpenAI) or new platforms (like Apple Vision Pro) are enabling. The first people to build simple tools or services on new platforms always win the biggest share. Stay active in developer forums and early-adopter communities to see where the smart money is moving before it hits the mainstream news.',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    },
    {
      id: 'a20',
      title: 'How to Build Long-Term Income Using Digital Opportunities',
      slug: 'long-term-digital-income-blueprint',
      excerpt: 'Move from "Hustling" to "Investing" with a decade-long digital vision.',
      content: 'Long-term income is about building "Compound Interests." Instead of jumping from one trend to another, pick a vertical and build a moat. A "Moat" can be a deep brand, a proprietary dataset, or a massive email list. By consistently adding value to the same audience for 5-10 years, you build an asset that grows in value and produces predictable income, regardless of short-term market fluctuations.',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1611974714851-48d1c793139d?auto=format&fit=crop&q=80&w=800',
      author: 'IncomeLab Editorial',
      createdAt: new Date().toISOString()
    }
  ],
  products: [
    // --- 30 PREMIUM PRODUCTS ---
    {
      id: 'p1',
      name: 'AI Tool Arbitrage Masterclass',
      slug: 'how-to-make-money-with-ai-tools',
      description: 'Master the rising demand for AI-driven services and tools.',
      price: 15500,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=600',
      type: 'Course',
      features: ['Content Automation', 'AI Video Workflow', 'SaaS Arbitrage'],
      targetAudience: 'Freelancers & Techies',
      problemSolved: 'Working long hours for low pay while others use AI to 10x output.',
      fullSalesCopy: 'Artificial Intelligence is no longer a luxury; it is the new standard for income. This masterclass teaches you how to identify high-paying tasks that can be automated with AI. We show you how to act as the "operator" between high-value corporate needs and AI tools, allowing you to charge professional rates for work that takes minutes to complete.',
      downloadUrl: '#'
    },
    {
      id: 'p2',
      name: 'The Living Room CEO Blueprint',
      slug: 'how-to-start-a-business-from-home',
      description: 'Build a million-dollar business with zero rent and zero commute.',
      price: 12000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=600',
      type: 'Blueprint',
      features: ['Home-Office Stack', 'Remote Sales Funnels', 'Distributed Hiring'],
      targetAudience: 'Stay-at-home parents & Remote workers',
      problemSolved: 'High overhead costs and the time-drain of a traditional office.',
      fullSalesCopy: 'Stop waiting for "permission" to build your empire. This blueprint provides the logistical and psychological framework for launching a professional enterprise from your home. We cover everything from setting up a professional digital presence to managing global teams from your kitchen table, ensuring your business looks like a corporation even if you are in your pajamas.',
      downloadUrl: '#'
    },
    {
      id: 'p3',
      name: 'Zero-Capital Startup Method',
      slug: 'how-to-start-a-business-with-no-money',
      description: 'How to build a business using only your existing skills and "Sweat Equity".',
      price: 7500,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Skill Audit Framework', 'Cold Outreach Scripts', 'Barter-to-Scale Strategy'],
      targetAudience: 'Unemployed graduates & Aspirants',
      problemSolved: 'The mental block that "you need money to make money".',
      fullSalesCopy: 'The biggest lie in entrepreneurship is that you need a bank loan to start. This toolkit teaches you the "Service-First" model—finding high-paying problems you can solve with your current skills. We provide the scripts to land your first pre-paid client, giving you the capital to fund your product or scale without ever taking a dime of debt.',
      downloadUrl: '#'
    },
    {
      id: 'p4',
      name: 'Property Profits Roadmap',
      slug: 'how-to-start-a-real-estate-business',
      description: 'The definitive guide to local and international real estate investment.',
      price: 55000,
      currency: 'NGN',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=600',
      type: 'Roadmap',
      features: ['Wholesale Secrets', 'Rental Yield Math', 'JV Contract Templates'],
      targetAudience: 'Serious Investors',
      problemSolved: 'Fear of property scams and the massive capital requirements of real estate.',
      fullSalesCopy: 'Real estate is the ultimate wealth protector against inflation. This roadmap takes you from "No Idea" to "First Deal" by teaching you the art of property sourcing and joint venture partnerships. Learn how to identify undervalued land, navigate legal documentation to avoid scams, and build a recurring rental income stream that outpaces the bank.',
      downloadUrl: '#'
    },
    {
      id: 'p5',
      name: 'Modern Online Business Bible',
      slug: 'how-to-start-an-online-business',
      description: 'The foundation for dropshipping, info-products, and digital services.',
      price: 25000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600',
      type: 'Guide',
      features: ['Global Payment Setup', 'Niche Validation', 'Growth Marketing'],
      targetAudience: 'Digital Entrepreneurs',
      problemSolved: 'Technical overwhelm and lack of a clear digital strategy.',
      fullSalesCopy: 'The internet is the only place where you can reach 5 billion people from one laptop. This bible provides the structural foundation for any digital venture. We walk you through product selection, building automated sales funnels, and setting up international payment systems that ensure you earn in hard currency regardless of where you are based.',
      downloadUrl: '#'
    },
    {
      id: 'p6',
      name: 'The Rookie Freelancer\'s Blueprint',
      slug: 'how-to-start-freelancing-with-no-experience',
      description: 'Get paid to learn. How to land your first $500 gig with zero portfolio.',
      price: 10000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=600',
      type: 'Roadmap',
      features: ['Mock Portfolio Creation', 'Upwork Hacks', 'Proposal Templates'],
      targetAudience: 'Students & Career Changers',
      problemSolved: 'The "No Experience = No Hires" paradox.',
      fullSalesCopy: 'Every expert was once a beginner. This blueprint shows you how to "manufacture" experience by building mock projects that prove your skill to clients. We give you the exact templates to use on platforms like Upwork and Fiverr to bypass the filter of experience and win high-paying contracts based on value and communication.',
      downloadUrl: '#'
    },
    {
      id: 'p7',
      name: 'Fashion Brand Architect',
      slug: 'how-to-start-a-fashion-brand',
      description: 'Turn your design dreams into a sold-out lifestyle brand.',
      price: 35000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1539109132314-d4a8c1738d45?auto=format&fit=crop&q=80&w=600',
      type: 'Course',
      features: ['Manufacturer Sourcing', 'Instagram Sales System', 'Influencer Strategy'],
      targetAudience: 'Creatives & Fashionistas',
      problemSolved: 'High production waste and difficulty finding a loyal customer base.',
      fullSalesCopy: 'The fashion industry is dominated by those who understand "The Hype." This course teaches you how to design for a specific niche, find reliable manufacturers who won\'t ruin your fabrics, and use viral social media marketing to create a "drop" culture that sells out your inventory in minutes.',
      downloadUrl: '#'
    },
    {
      id: 'p8',
      name: 'AI Learning Path: 0 to Hero',
      slug: 'how-to-learn-ai',
      description: 'Master the skills that companies are paying 6-figure salaries for.',
      price: 18000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=600',
      type: 'Guide',
      features: ['Prompt Engineering 101', 'AI Agents Setup', 'LLM Integration'],
      targetAudience: 'Professionals & Students',
      problemSolved: 'The fear of being left behind in the AI-driven job market.',
      fullSalesCopy: 'AI won\'t replace humans, but humans who use AI will replace those who don\'t. This path is designed for non-technical people who want to become AI power users. We skip the heavy math and go straight to practical application—teaching you how to prompt, how to build custom GPTs, and how to integrate AI into any workflow for massive productivity.',
      downloadUrl: '#'
    },
    {
      id: 'p9',
      name: 'FX Trading Fundamentals',
      slug: 'how-to-learn-forex-trading',
      description: 'Master the $6 trillion-a-day market without blowing your account.',
      price: 45000,
      currency: 'NGN',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1611974714851-48d1c793139d?auto=format&fit=crop&q=80&w=600',
      type: 'Course',
      features: ['Risk Management 101', 'Price Action Secrets', 'Broker Selection'],
      targetAudience: 'Aspiring Traders',
      problemSolved: 'Losing money to emotional trading and lack of a proven strategy.',
      fullSalesCopy: 'Forex is not a gamble; it is a game of probability and discipline. This course focuses on the "Professional Trader" mindset. We teach you how to read charts like a pro, manage your risk so one loss never wipes you out, and identify high-probability setups that the banks use to profit in the currency markets.',
      downloadUrl: '#'
    },
    {
      id: 'p10',
      name: 'Photoshop Design Foundations',
      slug: 'how-to-learn-photoshop-for-beginners',
      description: 'Go from zero to pro designer in 30 days.',
      price: 15000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=80&w=600',
      type: 'Roadmap',
      features: ['Layer Mastery', 'Photo Retouching', 'Social Media Asset Design'],
      targetAudience: 'Aspiring Designers',
      problemSolved: 'Steep learning curve of professional design software.',
      fullSalesCopy: 'The world runs on visuals. This roadmap cuts through the 90% of features you don\'t need and teaches you the 10% that produce 90% of the results. By the end of this course, you will have a portfolio of high-quality designs that you can use to sell your services to brands and businesses globally.',
      downloadUrl: '#'
    },
    {
      id: 'p11',
      name: 'The Ghostwriting Goldmine',
      slug: 'how-to-start-a-ghostwriting-business',
      description: 'Get paid to write for the world\'s busiest and most influential people.',
      price: 22000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=600',
      type: 'Guide',
      features: ['Voice Matching Skills', 'Executive Prospecting', 'High-Ticket Pricing'],
      targetAudience: 'Writers & Creators',
      problemSolved: 'Low-paying content writing and the "Starving Artist" syndrome.',
      fullSalesCopy: 'Executives have the ideas but no time to write. That is where you come in. This guide teaches you how to position yourself as a "Strategic Partner" rather than a writer. Learn how to charge ₦500k+ per project by capturing a CEO\'s voice and turning their thoughts into viral articles and best-selling books.',
      downloadUrl: '#'
    },
    {
      id: 'p12',
      name: 'Clothing Retail Blueprint',
      slug: 'how-to-start-a-clothing-business',
      description: 'Start a high-margin clothing business with minimal inventory risk.',
      price: 18000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Vendor Directory', 'Pre-order Models', 'WhatsApp Marketing'],
      targetAudience: 'Fashion Entrepreneurs',
      problemSolved: 'Tying up too much cash in unsold stock.',
      fullSalesCopy: 'You don\'t need a physical boutique to dominate the clothing market. This toolkit teaches you the "Lean Inventory" model. Learn how to source high-quality trending pieces, build a pre-order system that funds your stock, and use WhatsApp and Instagram to build a loyal customer base that buys every new collection you drop.',
      downloadUrl: '#'
    },
    {
      id: 'p13',
      name: 'Nigeria Digital Income Goldmine',
      slug: 'how-to-make-money-online-in-nigeria',
      description: 'The verified manual for earning Naira and Dollars in today\'s economy.',
      price: 10000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1542601906960-da0eddd7e93e?auto=format&fit=crop&q=80&w=600',
      type: 'Guide',
      features: ['Naira Devaluation Protection', 'Verified Remote Platforms', 'Payment Bypasses'],
      targetAudience: 'Every ambitious Nigerian',
      problemSolved: 'Naira devaluation and the lack of verified local opportunities.',
      fullSalesCopy: 'Stop looking for "scams" and start looking for systems. This manual is a filtered list of only the most reliable ways to earn online as a Nigerian. From selling digital products on local platforms to earning in Dollars via international remote work, this is your survival and thriving guide for the current economic climate.',
      downloadUrl: '#'
    },
    {
      id: 'p14',
      name: 'Google & YouTube Cashflow',
      slug: 'how-to-make-money-on-google-in-nigeria',
      description: 'Master SEO, AdSense, and the YouTube algorithm to earn USD.',
      price: 28000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?auto=format&fit=crop&q=80&w=600',
      type: 'Course',
      features: ['Faceless YT Channels', 'Blogging for Profit', 'SEO Mastery'],
      targetAudience: 'Content Creators',
      problemSolved: 'Difficulty receiving international payments and low local ad rates.',
      fullSalesCopy: 'Google is the world\'s largest bank if you know the code. This course teaches you how to build assets that Google is forced to pay for. Learn how to create "Faceless" YouTube channels that earn ad revenue while you sleep, and how to build blogs that rank for high-value international keywords, bringing in Dollars every month.',
      downloadUrl: '#'
    },
    {
      id: 'p15',
      name: 'Logistics Business Blueprint',
      slug: 'how-to-start-a-logistics-business',
      description: 'The operational guide to delivery and transport services.',
      price: 40000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=600',
      type: 'Blueprint',
      features: ['Fleet Tracking Systems', 'Driver Trust Frameworks', 'Last-Mile Optimization'],
      targetAudience: 'Investors & Transport Moguls',
      problemSolved: 'High theft rates and operational chaos in local delivery.',
      fullSalesCopy: 'Logistics is the backbone of e-commerce. This blueprint shows you how to start with just 2 bikes and scale to a fleet. We cover the crucial "Trust Systems" to ensure your drivers don\'t run off, the software you need to manage orders in real-time, and how to partner with vendors for steady, recurring daily income.',
      downloadUrl: '#'
    },
    {
      id: 'p16',
      name: 'Commercial Farming Masterplan',
      slug: 'how-to-start-a-farming-business-in-nigeria',
      description: 'Practical agribusiness for crops and livestock.',
      price: 32000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&q=80&w=600',
      type: 'Roadmap',
      features: ['Cash Crop Selection', 'Agro-Market Access', 'Storage & Logistics'],
      targetAudience: 'Agro-investors & Farmers',
      problemSolved: 'Post-harvest losses and poor market pricing for produce.',
      fullSalesCopy: 'Farming is a business, not a hobby. This roadmap focuses on "Commercial Agriculture." Learn which crops have the highest ROI in Nigeria right now, how to secure your land from intruders, and how to find industrial buyers BEFORE you plant your first seed. Turn your land into an inflation-proof revenue machine.',
      downloadUrl: '#'
    },
    {
      id: 'p17',
      name: 'Passive Income Architect',
      slug: 'how-to-make-passive-income-online',
      description: 'Build automated systems that generate revenue 24/7.',
      price: 25000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1518433278981-11271f4a7c24?auto=format&fit=crop&q=80&w=600',
      type: 'Blueprint',
      features: ['Affiliate Automation', 'Digital Asset Flipping', 'Evergreen Funnels'],
      targetAudience: 'Professionals & Builders',
      problemSolved: 'Trading hours for dollars perpetually without an exit plan.',
      fullSalesCopy: 'If you don\'t find a way to make money while you sleep, you will work until you die. This architect guide is about decoupling your time from your income. Learn how to build digital systems that capture leads, sell products, and deliver value without your physical presence, allowing you to focus on growth or freedom.',
      downloadUrl: '#'
    },
    {
      id: 'p18',
      name: 'YouTube Growth Accelerator',
      slug: 'how-to-grow-a-youtube-channel-for-income',
      description: 'The science of viral content and channel monetization.',
      price: 20000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['CTR Optimization', 'Retention Scripting', 'Sponsorship Kits'],
      targetAudience: 'Aspiring YouTubers',
      problemSolved: 'Low views and stagnant subscriber counts.',
      fullSalesCopy: 'YouTube is a search engine, not just a video site. This accelerator teaches you how to "Hack" the algorithm by mastering the 3 pillars: Thumbnails, Titles, and Retention. Learn how to find trending topics before they blow up and build a channel that pays you through ads, affiliate links, and high-paying brand deals.',
      downloadUrl: '#'
    },
    {
      id: 'p19',
      name: 'Global Dropshipping Mastery',
      slug: 'how-to-start-drop-shipping-business',
      description: 'Sell international products to a global market without holding stock.',
      price: 35000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaad5b?auto=format&fit=crop&q=80&w=600',
      type: 'Course',
      features: ['Product Research Bots', 'FB/TikTok Ad Mastery', 'ZenDrop Integration'],
      targetAudience: 'E-commerce Entrepreneurs',
      problemSolved: 'High cost of purchasing and storing stock before selling it.',
      fullSalesCopy: 'Dropshipping isn\'t dead; it\'s just evolved. Learn the "High-Ticket" and "Branded" dropshipping strategies that actually work in 2026. We show you how to find reliable suppliers, build a high-converting Shopify store, and run profitable ad campaigns that bring in orders while you sleep, all without ever touching the product.',
      downloadUrl: '#'
    },
    {
      id: 'p20',
      name: 'The Digital Agency Toolkit',
      slug: 'how-to-sell-digital-services-online',
      description: 'How to white-label and sell premium services to global clients.',
      price: 30000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1557838923-2985c318be48?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Agency Automation', 'Sub-contracting Secrets', 'Retention Strategy'],
      targetAudience: 'Freelancers & Agency Owners',
      problemSolved: 'Low local rates and the difficulty of scaling a service business.',
      fullSalesCopy: 'Selling services is the fastest way to 6-figures, but only if you scale. This toolkit shows you how to "Arbitrage" talent—hiring experts to do the work while you focus on high-level sales and strategy. Learn how to package services like SEO, Web Dev, and Ads into monthly retainers of $1k - $5k per client.',
      downloadUrl: '#'
    },
    {
      id: 'p21',
      name: 'Cocoa Export Mastery: Nigeria Edition',
      slug: 'how-to-start-a-cocoa-export-business-in-nigeria',
      description: 'Step-by-step blueprint for sourcing, certifying, and exporting Cocoa beans.',
      price: 48500,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1579639782539-15ca69a8a605?auto=format&fit=crop&q=80&w=600',
      type: 'Blueprint',
      features: ['Buyer Acquisition Secrets', 'NEPC Documentation', 'Quality Control Labelling'],
      targetAudience: 'Export Entrepreneurs',
      problemSolved: 'Complex regulatory hurdles and lack of access to foreign buyers.',
      fullSalesCopy: 'Nigeria is the 4th largest cocoa producer globally, yet most locals are locked out of the export market. This blueprint provides the exact roadmap to acquiring your export license, sourcing premium beans from local farmers, and securing multi-ton contracts with buyers in Europe and North America.',
      downloadUrl: '#'
    },
    {
      id: 'p22',
      name: 'Nigeria Real Estate Empire',
      slug: 'how-to-start-a-real-estate-business-in-nigeria',
      description: 'Launch a property agency or investment firm in the Nigerian market.',
      price: 55000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&q=80&w=600',
      type: 'Blueprint',
      features: ['Omonile Safety Guide', 'Property Wholesaling', 'Lagos Market Hotspots'],
      targetAudience: 'New Real Estate Agents',
      problemSolved: 'Fear of property scams and the massive capital needed for land banking.',
      fullSalesCopy: 'Lagos real estate appreciates faster than any other asset class in Africa. This guide teaches you how to enter the market with zero capital as a "Property Wholesaler." Learn the legal tricks to ensure land is genuine and how to command 5-10% commissions.',
      downloadUrl: '#'
    },
    {
      id: 'p23',
      name: 'High-Ticket Ghostwriting Agency',
      slug: 'how-to-start-a-ghostwriting-business-guide',
      description: 'Transition from low-pay writing to charging ₦500k+ per executive client.',
      price: 24000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1519791883288-dc8bd696e667?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Voice Matching Skills', 'CEO Cold-Outreach', 'Project Management'],
      targetAudience: 'Creative Writers',
      problemSolved: 'The income ceiling of content writing platforms like Fiverr/Upwork.',
      fullSalesCopy: 'CEOs have the vision but no time to write. This ghostwriting toolkit shows you how to position yourself as a strategic voice partner. Learn the pricing models used by the top 1% of ghostwriters to earn executive-level income.',
      downloadUrl: '#'
    },
    {
      id: 'p24',
      name: 'E-com Apparel Blueprint',
      slug: 'how-to-start-a-clothing-business-online-blueprint',
      description: 'Start a clothing brand using the micro-inventory and pre-order model.',
      price: 19500,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=600',
      type: 'Blueprint',
      features: ['Social Commerce Funnels', 'Vendor Sourcing', 'Brand Storytelling'],
      targetAudience: 'Lifestyle Entrepreneurs',
      problemSolved: 'High overhead costs of physical shops and unsold inventory waste.',
      fullSalesCopy: 'E-commerce in Africa is exploding. This blueprint skips the "Rent and Stock" model and goes straight to "Direct-to-Consumer." Learn how to use pre-orders to fund your production so you never lose money on unsold clothing.',
      downloadUrl: '#'
    },
    {
      id: 'p25',
      name: 'The Fresh Start Freelancer',
      slug: 'how-to-start-freelancing-with-no-experience-guide',
      description: 'Get hired based on potential. How to win global jobs with 0 previous clients.',
      price: 11000,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=600',
      type: 'Roadmap',
      features: ['Shadow Work Strategy', 'Profile SEO', 'The First-Gig Script'],
      targetAudience: 'Students & Career Starters',
      problemSolved: 'The "Need experience for a job, need a job for experience" trap.',
      fullSalesCopy: 'You don\'t need a CV; you need a Proof of Work. This roadmap teaches you how to build "Shadow Projects" that demonstrate your skill to international employers and win your first $100 contract within weeks.',
      downloadUrl: '#'
    },
    {
      id: 'p26',
      name: 'Creator Revenue Systems',
      slug: 'how-to-start-creating-content-for-income-guide',
      description: 'Turn your attention into an asset. A masterclass in content monetization.',
      price: 15500,
      currency: 'NGN',
      category: CategoryType.TECH,
      image: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Hook Writing Science', 'Short-form Monetization', 'Brand Deal Kit'],
      targetAudience: 'Aspiring Influencers',
      problemSolved: 'Posting content for months with zero engagement or income.',
      fullSalesCopy: 'Views are vanity; cashflow is sanity. This guide stops the "Posting and Praying" cycle. We teach you the science of viral hooks and 5 different ways to monetize your followers without needing a massive audience.',
      downloadUrl: '#'
    },
    {
      id: 'p27',
      name: 'Digital Course Architect',
      slug: 'how-to-make-money-teaching-online-courses-guide',
      description: 'Package your knowledge into a high-converting digital product.',
      price: 28000,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=600',
      type: 'Roadmap',
      features: ['Curriculum Design', 'Selar/Gumroad Mastery', 'Sales Funnel Build'],
      targetAudience: 'Experts & Teachers',
      problemSolved: 'Trading time for money as a tutor or consultant.',
      fullSalesCopy: 'The knowledge economy is a billion-dollar industry. This roadmap shows you how to structure your lessons for high completion rates and set up an automated sales funnel that brings in students 24/7.',
      downloadUrl: '#'
    },
    {
      id: 'p28',
      name: 'Passive Affiliate Funnels',
      slug: 'how-to-start-affiliate-marketing-for-beginners-guide',
      description: 'Build a traffic machine that sells other people\'s products for commission.',
      price: 15000,
      currency: 'NGN',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1434626881859-194d67b2b86f?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['SEO for Affiliates', 'Click-through Mastery', 'Email Automation'],
      targetAudience: 'Side-Hustlers',
      problemSolved: 'Low-quality affiliate programs and zero traffic to sales links.',
      fullSalesCopy: 'Affiliate marketing is about building trust. This toolkit shows you how to select high-paying products and how to use free SEO and Social Media traffic to drive sales while you sleep.',
      downloadUrl: '#'
    },
    {
      id: 'p29',
      name: 'Digital Product Factory',
      slug: 'how-to-sell-digital-products-online-guide',
      description: 'Create and sell templates, Ebooks, and software presets globally.',
      price: 22500,
      currency: 'NGN',
      category: CategoryType.DIGITAL_ASSETS,
      image: 'https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Canva Product Design', 'Automated Delivery', 'Global Pricing Strategy'],
      targetAudience: 'Digital Nomads',
      problemSolved: 'The technical complexity of setting up a digital storefront.',
      fullSalesCopy: 'Sell once, profit forever. This toolkit removes the tech barrier. Learn how to create high-value assets in Canva and scale a ₦1,000 product into a ₦1,000,000 monthly business.',
      downloadUrl: '#'
    },
    {
      id: 'p30',
      name: 'The Investor-Ready Business Plan',
      slug: 'how-to-write-a-business-plan-step-by-step-guide',
      description: 'Draft a professional business plan that wins grants and bank loans.',
      price: 12500,
      currency: 'NGN',
      category: CategoryType.BUSINESS,
      image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=600',
      type: 'Toolkit',
      features: ['Financial Projection Sheets', 'SWOT Analysis Builder', 'Pitch Deck Template'],
      targetAudience: 'New Entrepreneurs',
      problemSolved: 'Difficulty formalizing business ideas and failing to secure funding.',
      fullSalesCopy: 'Investors fund plans. This toolkit provides a fill-in-the-blank structure for a professional business plan. Learn how to calculate your market size and create a pitch deck that gets results.',
      downloadUrl: '#'
    }
  ],
  siteSettings: {
    heroTitle: 'Learn How to Build Real Income from Business, Tech & Digital Assets',
    heroSubtitle: 'Practical, step-by-step guides, tools, and blueprints designed for people who want real results — not hype.',
    announcement: '🚀 New Course: The 2026 Digital Asset Masterclass is now live!'
  }
};